import os

chlorophyta_genera = {
    "Acetabularia",
    "Actinastrum",
    "Ankistrodesmus",
    "Anthrodiella",
    "Apatococcus",
    "Aphanochaete",
    "Aphanochaetopsis",
    "Aphanochaeton",
    "Aphanochlamys",
    "Aphanochaete",
    "Aphanochaetopsis",
    "Aphanochaeton",
    "Aphanochlamys",
    "Apjohnia",
    "Archeochlamys",
    "Astrephomene",
    "Astrochlamys",
    "Astrolophos",
    "Azadinium",
    "Basichlamys",
    "Bathmodiolus",
    "Blepharisma",
    "Borodinellopsis",
    "Borziella",
    "Borziella",
    "Botryococcus",
    "Botrydium",
    "Bracteacoccus",
    "Braunella",
    "Brevisonus",
    "Bryopsis",
    "Bryopsidella",
    "Bryopsidium",
    "Bryopsis",
    "Bryopsidella",
    "Bryopsidium",
    "Bumilleriopsis",
    "Carteria",
    "Chamaedoris",
    "Chlamydocapsa",
    "Chlamydomonas",
    "Chlorogonium",
    "Chlorosarcinopsis",
    "Chodatodesmus",
    "Chodatodesmus",
    "Choristocarpus",
    "Chromochloris",
    "Chroomonas",
    "Chrysosphaerella",
    "Cladophora",
    "Coelastrum",
    "Concentricystis",
    "Craterosphaerella",
    "Cruoria",
    "Ctenocladus",
    "Ctenochloris",
    "Ctenococcus",
    "Cyclidiopsis",
    "Cyclotella",
    "Dactylococcus",
    "Dasycladus",
    "Desmidium",
    "Dictyochloropsis",
    "Diplosphaera",
    "Diplotaenium",
    "Draparnaldiopsis",
    "Draparnaldia",
    "Echinosphaeridium",
    "Ectocarpus",
    "Ellipsoidion",
    "Elmohamadya",
    "Eremosphaera",
    "Fossigerminisporites",
    "Fragilaria",
    "Fritschiella",
    "Geminella",
    "Geminella",
    "Gloeotilopsis",
    "Gloeocystis",
    "Gloeochaete",
    "Gloeocystis",
    "Gloeochaete",
    "Gloeothece",
    "Gloeobotrys",
    "Gloeotila",
    "Gonatozygon",
    "Gonium",
    "Gratulabacter",
    "Grelleriella",
    "Halochlorococcum",
    "Hantzschia",
    "Hantzschia",
    "Haematococcus",
    "Heleococcus",
    "Helicosporidium",
    "Hormidium",
    "Hydrurus",
    "Hydrodictyon",
    "Klebsormidium",
    "Korshikoviella",
    "Korshikovia",
    "Korshikovia",
    "Leptosira",
    "Mallomonas",
    "Marvania",
    "Mastogloia",
    "Micractinium",
    "Monodus",
    "Nannochloropsis",
    "Nephrocytium",
    "Nephrocytium",
    "Nephroselmis",
    "Nephroselmis",
    "Nephrospora",
    "Netrium",
    "Oocardium",
    "Oocystis",
    "Oocystopsis",
    "Oosphaerella",
    "Ostreococcus",
    "Palmellopsis",
    "Palmogloea",
    "Palmophyllum",
    "Pandorina",
    "Parachloris",
    "Paradoxia",
    "Pediastrum",
    "Pediatrum",
    "Pediatrurn",
    "Pediastrum",
    "Pelmatosphaera",
    "Pentochloris",
    "Pentalamina",
    "Perisporangium",
    "Phacotus",
    "Phaeosphaerion",
    "Phycopeltis",
    "Phyllosiphon",
    "Physolinum",
    "Picocystis",
    "Picochlorum",
    "Picochlorum",
    "Picocystis",
    "Placotrochus",
    "Planctonema",
    "Planothidium",
    "Plastochlamys",
    "Platyasterias",
    "Platygyra",
    "Pleurochloris",
    "Pleurococcus",
    "Pleurodiscus",
    "Pleurodiscus",
    "Pleurodiscus",
    "Pleurogaster",
    "Pleurogaster",
    "Pleurophacus",
    "Pleurophacus",
    "Pleurotaenium",
    "Pleurotaenium",
    "Pleurotaenium",
    "Pluricoccus",
    "Polarella",
    "Polarella",
    "Polyblepharides",
    "Polychloris",
    "Polyphysa",
    "Polytrichastrum",
    "Polyzonium",
    "Porphyridium",
    "Prasinocladus",
    "Prasiola",
    "Prasiolopsis",
    "Prasiolopsis",
    "Prasinoxanthin",
    "Prasinocladus",
    "Pseudochlorococcum",
    "Pseudopediastrum",
    "Pseudotetra",
    "Pseudotetraedriella",
    "Pyrobotrys"
    }
   

genera_in_dinophyta = {
    "Abyssodinium",
    "Acanthodinium",
    "Amphidiniopsis",
    "Amylax",
    "Apocalathium",
    "Attheya",
    "Biecheleria",
    "Blastodinium",
    "Briarosaccus",
    "Cachonina",
    "Carpodinium",
    "Chondrococcus",
    "Cryptoperidinium",
    "Diplopsalis",
    "Dissodinium",
    "Eugymnodinium",
    "Fibrocapsa",
    "Glenodinium",
    "Glenodiniopsis",
    "Gonyaulax",
    "Heterocapsa",
    "Leptodinium",
    "Lepidodinium",
    "Lophodinium",
    "Luciella",
    "Mallomonas",
    "Nematodinium",
    "Oxidinium",
    "Pentapharsodinium",
    "Peridinium",
    "Peridiniopsis",
    "Polykrikos",
    "Proterythropsis",
    "Pyrocystis",
    "Togula",
    "Trachyhystrichosphaera",
    "Tripos",
    "Wardium",
    # Add more genera here if needed
}
genera_in_euglenophyta = {
    "Anisonema",
    "Astasia",
    "Colacium",
    "Cryptoglena",
    "Cryptoglenoides",
    "Cryptoglenopsis",
    "Distigma",
    "Dylakosoma",
    "Entosiphon",
    "Euglena",
    "Euglenaria",
    "Euglenidium",
    "Euglenopsis",
    "Euglenophacus",
    "Eutreptia",
    "Eutreptiella",
    "Lepocinclis",
    "Menoidium",
    "Monomorphina",
    "Peranema",
    "Phacus",
    "Rhabdomonas",
    "Rhabdosiga",
    "Strombomonas",
    "Trachelomonas",
}
genera_in_glaucophyta = {
    "Cyanophora",
    "Glaucocystis",
    "Glaucosphaera",
    "Cyanoptyche",
    "Glaucospira",
    "Gloeochaete",
    "Cyanophacus",
    "Cyanophorella",
    "Cyanophoropsis",
}

genera_in_amoeba = [
    "Actinophrys",
    "Allovahlkampfia",
    "Arachnula",
    "Asterocorys",
    "Balantidium",
    "Bipalium",
    "Centropyxis",
    "Chaos",
    "Cochliopodium",
    "Dermamoeba",
    "Difflugia",
    "Didinium",
    "Echinostelium",
    "Euglypha",
    "Flabellula",
    "Foraminifera",
    "Gromia",
    "Heterolobosea",
    "Hydramoeba",
    "Lecythium",
    "Mayorella",
    "Megalamoeba",
    "Metachaos",
    "Myxogastria",
    "Pelomyxa",
    "Phreatamoeba",
    "Platyamoeba",
    "Polychaos",
    "Sarcodina",
    "Sorocelis",
    "Thecamoeba",
    "Trichamoeba",
    "Vannella",
    "Vexillifera",
    "Xenophyophorea",
    # Add more genera here if needed
]


genera_in_achnanthidiaceae = {
    "Achnanthes",
    "Achnanthidium",
    "Amphora",
    "Cavinula",
    "Cocconeis",
    "Cymbella",
    "Denticula",
    "Diploneis",
    "Encyonema",
    "Fistulifera",
    "Fragilaria",
    "Gomphonema",
    "Luticola",
    "Navicula",
    "Nitzschia",
    "Planothidium",
    "Rossithidium",
    "Stauroneis",
    "Surirella",
    # Add more genera here if needed
}

genera_tetrasporaceae = [
    "Apiocystis",
    "Tetraspora",
    "Delesseria",
    "Solieria",
    "Chondrus",
    "Ahnfeltiopsis",
    "Gigartina",
    "Mastocarpus",
    "Calliblepharis",
    "Cryptopleura",
    "Gracilariopsis",
    "Galaxaura",
    "Gymnogongrus",
    "Herposiphonia",
    "Neogoniolithon",
    "Pterocladia",
    "Ralfsia",
    "Spyridia",
    "Tetrasporopsis",
    "Falkenbergia",
    "Goniotrichum",
    "Petrocelis",
    "Rhodymenia",
    "Thamnoclonium",
    "Halarachnion",
    "Mazaedium",
    "Nitophyllum",
    "Pterothamnion",
    "Sarcophyllis",
    "Streblonema",
    "Trichogloea",
    "Wilsonosiphonia",
    "Dasyphloea",
    "Gomontia",
    "Herposiphonia",
    "Martensia",
    "Phyllophora",
    "Suhria",
    "Ptilophora",
    "Physematium",
    "Gloiosaccion",
    "Thorea"
    # You can continue adding more genera as needed
]

genera_catenulaceae = {
    "Catenula",
    "Stenostomum",
    "Rhynchoscolex",
    "Prorhynchoides",
    "Microstomum",
    "Rhamnostomum",
    "Stenostomoides",
    "Stenostomopsis",
    "Neocatenula",
    "Paracatenula",
    "Limnocatenula",
    "Sphincterostomum",
    "Zeldia",
    "Winkleria",
    "Prostomum",
    "Stenostomum",
    "Rugaho",
    "Catoscopium",
    "Chaetonotus",
    "Rhynchomesostoma",
    "Crenobia",
    "Diplodasys",
    "Stenostoma",
    "Neoprotoplanella",
    "Rhynchodemus",
    "Catenicella",
    "Cateniphagus",
    "Dichotomomacrostomum",
    "Catenodiplodasys",
    "Catenoporus",
    "Catenoplana",
    "Catenuloides",
    "Catenulostomum",
    "Cratera",
    "Echinocatenula",
    "Enchelidium",
    "Mesostoma",
    "Opistomum",
    "Paropisthomon",
    "Prorhynchus",
    "Rhynchozoon",
    "Spathidium",
    "Uteriporpa"
    # You can continue adding more genera as needed
}


base_path = "/media/chasuelt/MICROBES/microbe_images/"
outpath = "/media/chasuelt/MICROBES/organized"

for dirname in os.listdir(base_path):
    print(dirname)
    """
    if dirname in genera_tetrasporaceae:
        print("moving: ", dirname)
        if not os.path.exists(os.path.join(outpath, "tetrasporaceae")):
            os.mkdir(os.path.join(outpath, "tetrasporaceae"))
        os.rename(os.path.join(base_path, dirname), os.path.join(outpath, "tetrasporaceae", dirname))
    elif dirname in genera_in_amoeba:
        if not os.path.exists(os.path.join(outpath, "amoeba")):
            os.mkdir(os.path.join(outpath, "amoeba"))
        print("moving: ", dirname)
        os.rename(os.path.join(base_path, dirname), os.path.join(outpath, "amoeba", dirname))
    elif dirname in genera_in_dinophyta:
        if not os.path.exists(os.path.join(outpath, "dinophyta")):
            os.mkdir(os.path.join(outpath, "dinophyta"))
        print("moving: ", dirname)
        os.rename(os.path.join(base_path, dirname), os.path.join(outpath, "dinophyta", dirname))
    elif dirname in genera_in_euglenophyta:
        if not os.path.exists(os.path.join(outpath, "euglenophyta")):
            os.mkdir(os.path.join(outpath, "euglenophyta"))
        print("moving: ", dirname)
        os.rename(os.path.join(base_path, dirname), os.path.join(outpath, "euglenophyta", dirname))
    elif dirname in genera_catenulaceae:
        if not os.path.exists(os.path.join(outpath, "catenulaceae")):
            os.mkdir(os.path.join(outpath, "catenulaceae"))
        print("moving: ", dirname)
        os.rename(os.path.join(base_path, dirname), os.path.join(outpath, "catenulaceae", dirname))
"""




